// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKaef_CIzmhnomBxSx5s0oJ9QiB8sQczw',
    appId: '1:44810574324:web:f86c303ccba70bbc8d41a1',
    messagingSenderId: '44810574324',
    projectId: 'azodhacontactapp',
    authDomain: 'azodhacontactapp.firebaseapp.com',
    storageBucket: 'azodhacontactapp.appspot.com',
    measurementId: 'G-5Z7R500KS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT9rb61mjSwb-oouJOo_OsPfEmMCz_JwM',
    appId: '1:44810574324:android:4b08b9a9557d95fe8d41a1',
    messagingSenderId: '44810574324',
    projectId: 'azodhacontactapp',
    storageBucket: 'azodhacontactapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqxTjDNDhL99ND12LLiUwdXUyyxOJATf8',
    appId: '1:44810574324:ios:7d7f910837bec9878d41a1',
    messagingSenderId: '44810574324',
    projectId: 'azodhacontactapp',
    storageBucket: 'azodhacontactapp.appspot.com',
    iosBundleId: 'com.example.azodhaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqxTjDNDhL99ND12LLiUwdXUyyxOJATf8',
    appId: '1:44810574324:ios:c496a2e6711585658d41a1',
    messagingSenderId: '44810574324',
    projectId: 'azodhacontactapp',
    storageBucket: 'azodhacontactapp.appspot.com',
    iosBundleId: 'com.example.azodhaTask.RunnerTests',
  );
}
